### ISSUE TITLE
SIRF build fails on NiftyMoMo

### ISSUE THREAD

**Issue by evgueni-ovtchinnikov** [SyneRBI/SIRF#784] opened 2020-07-22 10:28 UTC
Building SIRF master on VM fails with
```
/home/sirfuser/devel/buildVM/sources/SIRF/src/Registration/NiftyMoMo/BSplineTransformation.cpp:1340:39: error: prototype for ‘NiftyMoMo::BSplineTransformation::PrecisionType* NiftyMoMo::BSplineTransformation::GetDVFGradientWRTTransformationParameters(nifti_image*)’ does not match any in class ‘NiftyMoMo::BSplineTransformation’
 BSplineTransformation::PrecisionType* BSplineTransformation::GetDVFGradientWRTTransformationParameters( nifti_image* denseDVFIn )
                                       ^~~~~~~~~~~~~~~~~~~~~
In file included from /home/sirfuser/devel/buildVM/sources/SIRF/src/Registration/NiftyMoMo/BSplineTransformation.cpp:21:0:
/home/sirfuser/devel/install/include/sirf/NiftyMoMo/BSplineTransformation.h:90:49: error: candidate is: virtual NiftyMoMo::BSplineTransformation::PrecisionType* NiftyMoMo::BSplineTransformation::GetDVFGradientWRTTransformationParameters(nifti_image*, nifti_image*)
   virtual BSplineTransformation::PrecisionType* GetDVFGradientWRTTransformationParameters( nifti_image* denseDVFIn, nifti_image* sourceImage );
                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by KrisThielemans** [comment] 2020-07-22 10:36
This was flagged up by @rijobro as a potential problem, and indeed it's there 😢 

note that it got the include file from `/home/sirfuser/devel/install/include/sirf/NiftyMoMo/BSplineTransformation.h`. Solution is therefore to
`rm -rf /home/sirfuser/devel/install/include/sirf/NiftyMoMo`

I guess we will have to put this in `SyneRBI/UPDATE_VM.sh`

**Comment by rijobro** [comment] 2020-07-22 10:38
Yup, sorry about this. See https://github.com/SyneRBI/SIRF/issues/783.

**Comment by evgueni-ovtchinnikov** [comment] 2020-07-22 11:07
thanks!

**Comment by paskino** [comment] 2021-01-21 11:57
I [stumbled ](https://github.com/SyneRBI/SyneRBI_VM/issues/172)upon this problem building SIRF master after I built v2.2.0. Maybe it's something for SIRF's CMake to remove that directory rather than UPDATE.sh?

Actually, we could delete all `sirf/include` directory?

**Comment by KrisThielemans** [comment] 2021-01-21 12:00
I can't see us doing this in CMake (it'd be rather weird to have a build wipe some of your install), but of course the UPDATE.sh script could easily do that.

**Comment by rijobro** [comment] 2021-01-21 12:22
Sorry that this has caused so many problems. Might be easier to address the problem [this way](https://github.com/SyneRBI/SIRF/issues/783#issuecomment-663034797) as it would be tidier and more future proof.

**Comment by paskino** [comment] 2021-02-02 08:12
What about the SuperBuild to remove the directory if present?

**Comment by rijobro** [comment] 2021-02-02 09:29
As @KrisThielemans , could go in the UPDATE.sh script, but shouldn't really go in the build/install instructions. Would be expected for either of those steps to be deleting folders in the install location.

**Comment by KrisThielemans** [comment] 2021-02-02 09:44
I find deletinagreed.  things in an install directory a bit scary. You don't know what the user has done or wants to do. 

I suspect that there are few people left who haven't deleted this themselves, or wouldn't be using the VM `UPDATE.sh`. Possibly we could create a "pre-compile" step that warns about it and stops the compilation, but I can see this eating up your time.

**Comment by paskino** [comment] 2021-02-02 14:34
This problem prevents SIRF to build in the SuperBuild throwing a very strange error. I could put the fix in `UPDATE.sh` in the VM, but if you don't use the VM you will hit this problem.

I think this is mostly a SuperBuild bug and should be fixed there with a pre compile step.

**Comment by KrisThielemans** [comment] 2021-02-02 14:45
It is not a SuperBuild bug. It is a SIRF bug that it looks for include files in the wrong place (you should never go and find things in the install directory first, before looking in the source directory). The problem is that it's hard to track down who puts the install path before the SIRF source, and then to fix that. See #783 for info.

As far as I understand, you will only hit this problem if you have built an old version of SIRF before, and are trying to install in the same location. This is something that we don't recommend on our wiki.

If it happens as well with a new version, then this problem becomes much more serious

**Comment by paskino** [comment] 2021-02-02 15:26
I believe the problem is [this ](https://github.com/SyneRBI/SIRF/blob/master/src/Registration/NiftyMoMo/CMakeLists.txt#L31)line.

`${NIFTYREG_INCLUDE_DIRS}` expands to `install/include` in my machine. 

The solution is just to remove `BEFORE` at that line, apparently.

**Closed** 2021-02-02 19:49 UTC
