### ISSUE TITLE
Reading in MR data with _all=True

### ISSUE THREAD

**Issue by ckolbPTB** [SyneRBI/SIRF#1200] opened 2023-06-12 14:20 UTC
When [reading in an MR raw data file](https://github.com/SyneRBI/SIRF/blob/a31f2d23c76ad43b36611a81e3b3e9f66ba296f6/src/xGadgetron/pGadgetron/Gadgetron.py#L847) using `_all=True` and then calling `dimensions()` or `number()` then different results are returned:
`number()` returns the number of all readouts, also noise calibration data
`dimensions()` returns only the readouts which are selected by [get_acquisition()](https://github.com/SyneRBI/SIRF/blob/a31f2d23c76ad43b36611a81e3b3e9f66ba296f6/src/xGadgetron/cGadgetron/include/sirf/Gadgetron/gadgetron_data_containers.h#L731)

In addition
`get_ISMRMRD_info('flags', range(AcquisitionData.number()))` and `get_ISMRMRD_info('flags')` lead to different results.

I understand that the definitions of which readouts to use based on the flags is necessary to be able to sort the data into a numpy array. Nevertheless, I find this behaviour confusing and might lead to many problems further down the processing pipeline. 

I am not sure yet how best to fix this, probably requires further discussions...

**Comment by evgueni-ovtchinnikov** [comment] 2023-06-19 14:55
For MR acquisition data to be treated as a multi-dimensional array, one has to ignore certain "irregular" readouts (of which I only ever encountered those involved in noise measurement, so I have no idea what other irregular ones are). Therefore, generally `number()` may be larger  than the respective dimension of the 3D array representation of the acquisition data.

As for the different output of `get_ISMRMRD_info()`, it was just a bug, now corrected.

I have to admit that the dimensionality of MR acquisition data is a very difficult issue to me as I have no idea about a lot of dimensions involved. The current 3D implementation was just the simplest for me and coherent with the way the SIRF client sends acquisitions to the Gadgetron server - as a sequence of 2D arrays. I heard there might be up to 11 dimensions, but I would need some examples (preferably C++) illustrating their purpose and use before I could try to come up with something more proper than the current simple 3D design.

**Comment by evgueni-ovtchinnikov** [comment] 2023-06-20 16:20
> We are currently only selecting data with a certain flag in [get_acquisition()](https://github.com/SyneRBI/SIRF/blob/a31f2d23c76ad43b36611a81e3b3e9f66ba296f6/src/xGadgetron/cGadgetron/include/sirf/Gadgetron/gadgetron_data_containers.h#L731). This means that image data without any flags is ignored.

I am afraid I cannot quite follow you here: `get_acquisition()` ignores acquisitions with flags 19, 23 and above. Acquisitions with zero flag are never ignored.

> Maybe it would make more sense to explicitly exclude noise data and keep the rest.

What about flags 23 and above? I have no idea what acquisitions with these flags are, but I very much doubt they should be allowed to impact the acquisitions algebra (e.g. `norm()`).

> Ideally there would be an option for the user to give their own set of "exclude" flags.

A very good idea, will definitely implement.

**Comment by ckolbPTB** [comment] 2023-06-21 09:11
> I am afraid I cannot quite follow you here: `get_acquisition()` ignores acquisitions with flags 19, 23 and above. Acquisitions with zero flag are never ignored.

Then I misunderstood the logic in `get_acquisition()` and I have to check again what the flags of my data were, which got ignored...

> What about flags 23 and above?
Probably ISMRMRD_ACQ_IS_DUMMYSCAN_DATA should not be part of the image data but for the rest it is not so obvious. ISMRMRD_ACQ_IS_RTFEEDBACK_DATA is for real-time feedback data and this could be part of the imaging data set. 

Maybe for consistency we could leave `TO_BE_IGNORED` as is (and maybe use `TO_BE_IGNORED` in `get_acquisition()`) and simply add the functionality for users to specify their own flags for `TO_BE_IGNORED`.

**Comment by NikEfth** [comment] 2023-07-25 17:39
Hi Evgueni, 

I am having several problems that to some degree are related with this problem. 
So, in brief I have a stack of spiral acquisitions that have been acquired differently and I try to find a consistent way to reconstruct them. 

In the simplest acquisition I have a kspac of 182 angles (or spokes as per radial terminology) x 96 partitions x 18 coils (or any other number) x 410 read out points. 
So, in this particular acquisition, the space should be [96, 182, 18, 410]. This is what I get from other toolboxes. 
SIRF gives me a [96*182, 18, 410] array which I guess should be fine. 

However, other acquisitions from the same scanner do not read correctly. 
For example in a similar case with 4 echos the space should have been [4, 96,182, 18, 410] or maybe [4*96*182, 18, 410] but I get [0, 32593, 860329040] and I have about 17471 acquisitions ignored. The get_ISMRMRD_info('kspace_encode_step_1') gives me 17472.

I find all these very confusing. 
It seems to me that SIRF tries to read the kspace as different acquisitions and ends up ignoring all of them. But I still cannot understand where this size comes from [0, 32593, 860329040]. 

I don't have problems only with multiple echos. I don't really know what confuses SIRF but some files are read somewhat correctly and others don't. 

Any ideas?

**Comment by NikEfth** [comment] 2023-07-25 17:40
I am keen to implement a ```merge``` function that will merge all acquisitions to a single k-space. But I don't know if that is the way forward.

**Comment by NikEfth** [comment] 2023-07-25 20:50
Quick update: 

Without using the Python interface, in cpp, the k-space is loaded correctly. At least without multiple echoes. 
The Acquisition vector has 17471 acquisitions of [15x410]. Which, as I understood, is how SIRF loads the data.

The same dataset from Python fails. 
I think that the ignore_mask is not loaded properly in the interface. 
Possibly: 
```void read(const std::string& filename_ismrmrd_with_ext, int all = 0,IgnoreMask ignore_mask = 0)```
takes an ```IgnoreMask```
but ``` acquisitions->read(file, all, ignored) ``` in ``` cGT_ISMRMRDAcquisitionsFromFile(const char* file, int all, int ignored)``` passes an ```int```.

 Maybe?

**Comment by evgueni-ovtchinnikov** [comment] 2023-07-26 14:06
`IgnoreMask` has a constructor from `size_t`, so `ignored` gets converted into an `IgnoreMask`.

Actually, as SWIG does not allow me to use `size_t` for `ignored`, I have now replaced `size_t` with `int` also in the definition of class `IgnoreMask` (using `size_t` there could be the reason for the errors). I also put printout for `ignored` bits in `cGT_ISMRMRDAcquisitionsFromFile` - please pull the update and try again with Python and let me know what bitmask is printed.

Thanks a lot for tackling this stuff, which was designed and implemented entirely by Johannes, so I am completely out of my depth there! I am relieved that C++ works, otherwise I would be panicking.

**Comment by NikEfth** [comment] 2023-07-26 14:33
This the the printed bitmask: ``` 1111 1110 1100 0100 0000 0000 0000 0000```. 
However, the file is still not loaded correctly. 
The size of the loaded k-space is (0, 21889, -1665160272).

**Comment by NikEfth** [comment] 2023-07-26 17:51
I think I have a good lead. 
When the ```flag()``` in the ```ISMRMRD::Acquisition``` in the ```AcquisitionsVector``` has the 29th bit 0 then in the Python the acqusitions are merged into a single k-space. For example in one file the first ```ISMRMRD::Acqusition``` has flag 64 followed by 0 for the rest and the size of k-space is correct. 

In another scan the```ISMRMRD::Acquisition``` flags have 29th bith 1. So the first acquisistion has flag 268435520 followed by 268435456. In this case the k-space in Python is wrong. 

What do you propose?

**Comment by NikEfth** [comment] 2023-07-26 19:16
Alright, I think I found the culprit. 
You set the ```IgnoreMask``` in the read functions but it is not stored in the ```MRAcquisitionData``` so when the functions as dimensions are called the default mask is applied. 
Either we need to store the ```IgnoreMask``` that was used to read the data or use them as input in every function that will scroll through the data. 

My opinion is to store it in the ```MRAcquisitionData``` but gradually introduce the input arguments in functions that may need to override the original.

**Comment by NikEfth** [comment] 2023-07-26 20:25
This is a very minimal set of changes that can make my acquisitions load in-full. 
Although, I have not processed anything yet. 

In ``` MRAcquisitionData::get_data(complex_float_t* z, int a, IgnoreMask ignore_mask)``` change to:
```
       if (!get_acquisition(a, acq, &ignore_mask)) {
``` 

In ```MRAcquisitionData``` add  a protected member mask. 

In ```IgnoreMask``` ```max``` should be made ```static```. 

In ``` void MRAcquisitionData::read(const std::string& filename_ismrmrd_with_ext, int all,	IgnoreMask ignore_mask)``` assign to: 
```
 mask = ignore_mask;
``` 
And more importantly:
```
	virtual int get_acquisition(unsigned int num,
			ISMRMRD::Acquisition& acq,
            const IgnoreMask* ignore_mask_p = nullptr) const
		{
			int ind = index(num);
			acq = *acqs_[ind];
            if (ignore_mask_p == nullptr)
                ignore_mask_p = &this->mask;
            if (ignore_mask_p->ignored(acq.flags()))
				return 0;
			return 1;
		}
```

There might be a couple of easy compilation errors to hunt down, but I with these few changes the rest of the code should stay the same.

**Comment by evgueni-ovtchinnikov** [comment] 2023-07-27 09:04
I am afraid I am not in favour of this kind of solution. For one thing, it compromises `const`ness. (I actually implemented similar approach first, but then changed it to the current one - see git log, commit 2b3dc2ff14b575822e3f5d20523c8cd1d2223291.)

Besides, you mentioned earlier that you only had problems in Python, not C++, did you not?

It might help me if you could explain the meaning of flags 23, 24 and 26 to 29. As far as other flags are concerned, I am firmly convinced that the default ignore mask is absolutely necessary for correct algebra and fill/as_array methods.

**Closed** 2023-12-07 16:30 UTC
Labels: bug, design
