### ISSUE TITLE
KOSMAPOSLReconstructor.set_up() failure

### ISSUE THREAD

**Issue by evgueni-ovtchinnikov** [SyneRBI/SIRF#654] opened 2020-05-12 11:20 UTC
In demo `hkem_reconstruction.py`,  `KOSMAPOSLReconstructor.set_up()` fails with error message 
```
ERROR: Error opening file 
```
apparently thrown by `stir::IterativeReconstruction::post_processing()`

**Comment by evgueni-ovtchinnikov** [comment] 2020-05-12 12:30
must be something to do with VM, works ok on Windows

**Comment by KrisThielemans** [comment] 2020-05-12 13:00
that would be weird. Are you sure your VM STIR was updated to 4.0.1?

**Comment by KrisThielemans** [comment] 2020-05-12 13:02
`update_VM.sh -t origin/master` would do the whole thing possibly, although with probably with the problem of the STIR tag, so `rm -rf ~/devel/buildVM/sources/STIR` first.

**Comment by KrisThielemans** [comment] 2020-05-12 21:08
confirmed on my updated VM.

**Comment by KrisThielemans** [comment] 2020-05-13 07:43
@evgueni-ovtchinnikov can you please clarify the calling sequence here? I can't immediately find where `post_processing` is called. Do we do that because STIR's `KOSMAPOSLReconstruction::set_up` is incomplete? It does look that way.

Do you know if it is thrown in `stir::IterativeReconstruction::post_processing()` or further in the chain? (e.g. `stir::KOSMAPOSLReconstruction::post_processing()`)?

**Comment by evgueni-ovtchinnikov** [comment] 2020-05-13 09:27
`KOSMAPOSLReconstruction::post_processing` is supposed to read anatomical images, but their filenames are empty.

**Comment by KrisThielemans** [comment] 2020-05-13 09:32
ok. if you'd be able to point to the line, it would help @danieldeidda 

Would resolving https://github.com/UCL/STIR/issues/537 solve the SIRF problem? (i.e. we'd no longer call `post_processing`)

**Comment by evgueni-ovtchinnikov** [comment] 2020-05-13 09:42
@danieldeidda line 224 in `KOSMAPOSLReconstruction.cxx` fails to read from file with empty name.

**Comment by danieldeidda** [comment] 2020-05-13 09:49
> 
> 
> @danieldeidda line 224 in `KOSMAPOSLReconstruction.cxx` fails to read from file with empty name.

Could it be because that member is now a vector? in the parfile we need to put the name inside {}

**Comment by KrisThielemans** [comment] 2020-05-13 11:20
@evgueni-ovtchinnikov could you try with https://github.com/UCL/STIR/pull/540?

**Comment by KrisThielemans** [comment] 2020-05-13 11:20
There's also the SIRF-Exercises I guess

**Comment by evgueni-ovtchinnikov** [comment] 2020-05-13 11:45
But that line in `post_processing` that throws the error is still there, and nothing added above it - why would it not throw now?

@danieldeidda: have you run `hkem_reconstruction.py` in `SIRF/examples/Python/PET`?

**Comment by KrisThielemans** [comment] 2020-05-13 12:23
> But that line in post_processing that throws the error is still there, and nothing added above it - why would it not throw now?

indeed, but you should no longer call it. You should just call set_up.

**Comment by evgueni-ovtchinnikov** [comment] 2020-05-13 14:19
if `post_processing` is not called, line 224 is not executed indeed - and `anatomical_prior_sptr` remains empty, causing seg fault in `set_up` when `estimate_stand_dev_for_anatomical_image` is called.

**Comment by KrisThielemans** [comment] 2020-05-13 14:24
ok. @danieldeidda your `set_up` should check if images/data are initialised properly. This might be tied with `set_defaults`.
For the SIRF demo, this seems to mean that there should be a call to `set_anatomical_image` (or whatever its called) before `set_up`?

**Comment by danieldeidda** [comment] 2020-05-13 15:32
> 
> 
> ok. @danieldeidda your `set_up` should check if images/data are initialised properly. This might be tied with `set_defaults`.
> For the SIRF demo, this seems to mean that there should be a call to `set_anatomical_image` (or whatever its called) before `set_up`?

yes this should be called before set_up(): 

set_anatomical_image_filenames(const std::string &arg)
{
  this->anatomical_image_filenames[0]  = arg;
}
@evgueni-ovtchinnikov sorry I haven't run anything on SIRF.

**Comment by danieldeidda** [comment] 2020-05-13 15:35
set_defaults() initialise the filename vector like the following:

`this->anatomical_image_filenames.push_back("");`

**Comment by evgueni-ovtchinnikov** [comment] 2020-05-13 16:22
In SIRF, we do not use filenames, we use SIRF's `KOSMAPOSLReconstructor` method `set_anatomical_prior` passing the anatomical image as the argument of type `ImageData`.

This is actually done in `hkem_reconstruction.py`, but you made few mistakes, or, rather, repeated the same mistake: for an `std::vector` `v` the assignment `v[i] = value` can only be (safely) used if `i` is less than the current size of `v`.

So, this is what you shoud do: replace one of your `set_anatomical_prior_sptr` methods with
```
template<typename TargetT>
void
KOSMAPOSLReconstruction<TargetT>::
set_anatomical_prior_sptr (shared_ptr<TargetT> arg, int index)
{
    int n = this->anatomical_prior_sptr.size();
    if (index < n)
        this->anatomical_prior_sptr[index] = arg;
    else
        this->anatomical_prior_sptr.push_back(arg);
}
```
and replace
```
       SD[i]=((double)sqrt(kStand_dev/(nv-1) ));
```
with
```
        int nsd = SD.size();
        double s = ((double)sqrt(kStand_dev/(nv-1) ));
        if (i < nsd)
            SD[i] = s;
        else
            SD.push_back(s);
```

**Comment by KrisThielemans** [comment] 2020-05-13 16:35
or (probably safer), have a method that first says how many there are. Then in the `set` function, check if you're not going out-of-bounds. could (later) have a method `set_anatomical_priors_sptrs(std::vector<...>) to set them all in one go. (maybe you have it already).

However, we should continue suggestions on this in the STIR PR.

**Comment by evgueni-ovtchinnikov** [comment] 2020-05-13 16:40
At any rate, it does not look to me like the use of several anatomical images has been well thought
through. I suggest we stick to STIR 4.0.0 for this SIRF release.

**Comment by KrisThielemans** [comment] 2020-05-13 16:48
I certainly didn't want to create a lot of stuff now to fix multi-image support in `stir::KOSMAPOSLReconstruction`, or even let SIRF support it.

I was after a minimal update that would do that. Maybe that isn't possible.

We cannot stick to STIR 4.0.0 as it's broken. We could stick to STIR 4.0.1 but then will have to say that `sirf::KOSMAPOSL` is currently broken (due to STIR changes).

summary:

**Comment by evgueni-ovtchinnikov** [comment] 2020-05-13 16:51
In that case let us do the quick fix of 4.0.1 that I suggested.

**Comment by KrisThielemans** [comment] 2020-05-15 15:49
@evgueni-ovtchinnikov would you be able to try with @danieldeidda's current https://github.com/UCL/STIR/pull/540

**Comment by KrisThielemans** [comment] 2020-05-19 18:08
@evgueni-ovtchinnikov still has a problem https://github.com/UCL/STIR/pull/540#issuecomment-630762273

This is caused by calling `post_processing`
https://github.com/SyneRBI/SIRF/blob/dcf7a4d37153f3d6334386255767e7d777f0aee6/src/xSTIR/cSTIR/cstir.cpp#L728-L729
which @danieldeidda worked hard to remove the need for in https://github.com/UCL/STIR/pull/540. Indeed, `KOSMAPOSL::post_processing` will fail as there are no filenames set.

I'm not sure though if we can remove the call to `post_processing`  for all STIR reconstruction algorithms. @evgueni-ovtchinnikov do you know?

**Comment by danieldeidda** [comment] 2020-05-20 09:06
I am a bit confused I thought the post_process() was not going to be called by SIRF. since anatomical_image_filenames is never defined in SIRF but sigm_m does, this check is always goin to throw that error. Should we remove it? we have the same with the anatomical prior in set_up()

**Comment by KrisThielemans** [comment] 2020-05-20 09:28
@danieldeidda yes indeed. that was my intention, but as the call to `post_process` is actually quite high up in the hierarchy, I'm not sure if removing it will not break something else. (We've only fairly recently tried to distinguish better between `post_processing` and `set_up` in STIR).

I've removed the call to `post_process`. Then `hkem_reconstruction.py` seems to work (at least, it doesn't fail). the SIRF ctests also work. Not sure if this is sufficient to know if this works for all recon algorithms though.

**Comment by KrisThielemans** [comment] 2020-05-20 09:52
I've gone through all `stir::*Reconstruction` post_processing functions. None of them does anything "essential" anymore that will break things if we don't call it. There's  2 issues https://github.com/UCL/STIR/issues/545 https://github.com/UCL/STIR/issues/543 which mean that it will be more unsafe not to call `post_processing` from SIRF, but I feel we should go ahead now, and fix those STIR issues asap and get a new STIR release out.

**Comment by KrisThielemans** [comment] 2020-05-21 17:41
I've run the demos. this all looks fine to me.

**Comment by KrisThielemans** [comment] 2020-05-22 09:50
@evgueni-ovtchinnikov I've merged the STIR PR onto STIR release_4.0 and create #666 (ominous number?). Could you please check?

**Comment by KrisThielemans** [comment] 2020-05-22 11:16
Closed with https://github.com/SyneRBI/SIRF/commit/d6e4fe0105b9289e29648f697bdba6a3d0b4fb64 and https://github.com/UCL/STIR/pull/540.

However, I believe this will mean that `sirf::KOSMAPOSL` will now require STIR 4.0.2 (to be released soon), as otherwise it will fail.

**Closed by KrisThielemans** 2020-05-22 11:16 UTC
