### ISSUE TITLE
libReg.a fails to link to Boost in Ubuntu 20.04

### ISSUE THREAD

**Issue by paskino** [SyneRBI/SIRF#1037] opened 2022-02-01 15:39 UTC
In https://github.com/SyneRBI/SIRF-SuperBuild/issues/649 it seems there is a linker error for `libReg.a` 

Apparently boost linking is taken care of by https://github.com/SyneRBI/SIRF/blob/6c0b1fe1e357b94b391a3d0ebc5a32a8f1b5f24d/src/Registration/cReg/CMakeLists.txt#L76-L87

The current `if` statement has been merged in [long ago](https://github.com/SyneRBI/SIRF/commit/ffdf0ca6e4dadcfc3bb98a0aa7bcd5307cff3762), before we used CMake 3.5.

Given that now we require CMake 3.9 I believe the `if` is not useful, probably harmful. I suggest to remove them in the [3 places](https://github.com/SyneRBI/SIRF/search?q=_Boost_IMPORTED_TARGETS&type=code) where this is done.

**Comment by KrisThielemans** [comment] 2022-02-01 15:46
`_Boost_IMPORTED_TARGETS`. is set by CMake https://github.com/Kitware/CMake/blob/9d439dfd1b7f8599905e687005dd8dc69921f4d2/Modules/FindBoost.cmake#L1391
I would guess that it never happens for us as our Boost and CMake version combination should always give them, (see [here](https://github.com/Kitware/CMake/blob/9d439dfd1b7f8599905e687005dd8dc69921f4d2/Modules/FindBoost.cmake#L1015) so you could get rid of the `if` I believe.  You can check in which branch of the `if` it goes.

However,  I think the problem is with `filesystem`. I see 2 possibly causes:
- we don't install boost/filesystem library
- we have incorrect dependencies. I think this is probably the case, see https://github.com/SyneRBI/SIRF/issues/429

**Comment by paskino** [comment] 2022-02-01 16:26
We do [install ](https://github.com/SyneRBI/SIRF-SuperBuild/blob/3c8679bda27af6d8ab1495029e97a5bb47300757/docker/build_gadgetron-ubuntu.sh#L8-L12)`libboost-filesystem-dev` 

It is arguably a problem with the Boost version? I don't think so because I'm building with `USE_SYSTEM_Boost=ON` so there shouldn't be another Boost around?

Ubuntu 18.04 should have [1.65](https://packages.ubuntu.com/bionic/libboost-all-dev), but in some messages during the build I could see 1.36 ([STIR's ](https://github.com/UCL/STIR/blob/a9d0baf732263c8e0ade63abe4ab03afd4216c26/CMakeLists.txt#L81)CMake output during config) and 1.48, which buffles me.

**Comment by KrisThielemans** [comment] 2022-02-01 16:48
> We do [install ](https://github.com/SyneRBI/SIRF-SuperBuild/blob/3c8679bda27af6d8ab1495029e97a5bb47300757/docker/build_gadgetron-ubuntu.sh#L8-L12)`libboost-filesystem-dev`

great

> We do [install ](https://github.com/SyneRBI/SIRF-SuperBuild/blob/3c8679bda27af6d8ab1495029e97a5bb47300757/docker/build_gadgetron-ubuntu.sh#L8-L12)`libboost-filesystem-dev`
> 
> It is arguably a problem with the Boost version? I don't think so because I'm building with `USE_SYSTEM_Boost=ON` so there shouldn't be another Boost around?
> 
> Ubuntu 18.04 should have [1.65](https://packages.ubuntu.com/bionic/libboost-all-dev), but in some messages during the build I could see 1.36 ([STIR's ](https://github.com/UCL/STIR/blob/a9d0baf732263c8e0ade63abe4ab03afd4216c26/CMakeLists.txt#L81)CMake output during config) and 1.48, 

We [require 1.36](https://github.com/SyneRBI/SIRF/blob/4bcf7c0a340eb438ad233702b9b6f764d50cbbf7/CMakeLists.txt#L93), which is probably what you see. Maybe STIR requires 1.48. not sure. Of course, I think we likely need more recent boost...


Not sure what's going on. I guess you'' find out if we really use the `boost::filesystem` et al. targets. If we do, I guess you want to do a `make VERBOSE=ON` after the first failure.

**Comment by KrisThielemans** [comment] 2022-03-12 17:48
I wonder now if this is because the Boost version was more recent than the CMake version (as discussed in https://github.com/SyneRBI/SIRF-SuperBuild/issues/667). Which CMake and Boost version was this using?

**Comment by paskino** [comment] 2022-09-26 11:58
@KrisThielemans is this still relevant?
AFAIK, the SuperBuild builds on Ubuntu 20.04 both on GHA and docker?

**Comment by KrisThielemans** [comment] 2022-09-26 17:10
> AFAIK, the SuperBuild builds on Ubuntu 20.04 both on GHA and docker?

yes. In fact, GHA is on `ubuntu-latest` I believe, which could be 22.04 by now.

I first thought we could merge db4479db6c915b9bb79a9aa34ed1a120d6c7728e via a PR to simplify our files, but I now think that this code could cover the case where CMake is older than Boost (in which case `FindBOOST.cmake` gives up and doesn't define the targets I think). I'm not 100% sure, but unless you want to investigate that, it might be easiest to just leave it in.

Of course, I have no idea what happened when you had this problem, so there might be some problem lurking somewhere, but finding out is going to be tough.

Summary : I'm fine with closing this issue.

**Closed** 2022-11-01 14:09 UTC
